<?php

use Illuminate\Database\Seeder;

class CompaniesTableSeeder extends Seeder {

	public function run()
	{
        /**
         * Note: Convert CSV files generated by Excel to UTF-8
         */
        
		// import company data
		$companies = file('resources/data/companies/companies.txt');

		foreach($companies as $company)
		{
			list($name, $full_name, $slug) = explode(';', trim($company));

			$data = array(
				'name'			=> $name,
				'full_name'		=> $full_name,
				'slug'			=> $slug,
				'created_at'	=> new DateTime,
				'updated_at'	=> new DateTime
			);
			
			DB::table('companies')->insert($data);
		}
	}
}