<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
        /**
         * Note: Convert CSV files generated by Excel to UTF-8
         */

		$this->call('AudiencesTableSeeder');
		$this->call('ArticlesTableSeeder');
		$this->call('CitiesTableSeeder');
		$this->call('CompaniesTableSeeder');
		$this->call('EventsTableSeeder');
		$this->call('JobsTableSeeder'); // TO BE REMOVED
		$this->call('OrganizersTableSeeder');
		$this->call('RegionsTableSeeder');
		$this->call('GroupsTableSeeder');
		$this->call('UserTableSeeder'); // TO BE REMOVED
	}

}