<?php

use Illuminate\Database\Seeder;

class OrganizersTableSeeder extends Seeder {

	public function run()
	{
        /**
         * Note: Convert CSV files generated by Excel to UTF-8
         */
        
		// import organizer data
		$organizers = file('resources/data/organizers.txt');

		foreach($organizers as $organizer)
		{
			list($name, $slug, $website, $featured, $meta_description, $profile) = explode(';', trim($organizer));

			$data = array(
				'name'				=> $name,
				'slug'				=> $slug,
				'website'			=> $website,
				'featured'			=> $featured,
				'meta_description'	=> $meta_description,
				'profile' 			=> $profile,
				'created_at'		=> new DateTime,
				'updated_at'		=> new DateTime
			);
			
			DB::table('organizers')->insert($data);
		}
	}
}